version: '2'
services:
  jbackend-app:
    image: jbackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mariadb://jbackend-mariadb:3306/jbackend?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://jbackend-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jbackend-elasticsearch:9200
    ports:
      - 8080:8080
  jbackend-mariadb:
    extends:
      file: mariadb.yml
      service: jbackend-mariadb
  jbackend-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jbackend-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
